# Generated by Django 5.2 on 2026-02-25 04:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ct_id', models.AutoField(primary_key=True, serialize=False)),
                ('ct_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('sw_id', models.AutoField(primary_key=True, serialize=False)),
                ('sw_uname', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=150)),
                ('reset_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyService',
            fields=[
                ('ss_id', models.AutoField(primary_key=True, serialize=False)),
                ('ss_name', models.CharField(max_length=100)),
                ('ss_date', models.DateTimeField(auto_now_add=True)),
                ('ss_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('In_id', models.AutoField(primary_key=True, serialize=False)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax amount for the product', max_digits=10)),
                ('warranty', models.IntegerField(help_text='Warranty in months')),
                ('description', models.TextField(blank=True, help_text='More Product details', null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('stock', models.IntegerField(default=0, help_text='Number of units in stock. Must be zero or positive.', validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category')),
                ('shop_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shopowner')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty', models.IntegerField(default=0)),
                ('customer_phone', models.CharField(blank=True, default='N/A', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='More details', null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.category')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopowner')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid'), ('WARRANTY', 'Warranty')], max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('product_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invoiceitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('shop_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shopowner')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('service', 'Service Request'), ('info', 'Info')], max_length=20)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('available_qty', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopowner')),
            ],
        ),
        migrations.CreateModel(
            name='ShopPurProd',
            fields=[
                ('sp_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('ONLINE', 'Online')], default='CASH', max_length=20)),
                ('sp_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('replacement', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
