# Generated by Django 5.2 on 2026-02-25 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='purchase_date',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
