# Generated by Django 5.2 on 2026-02-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='problem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
