# Generated by Django 5.2 on 2026-02-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_serviceinvoice_customer_serviceinvoice_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinvoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='service_invoices/'),
        ),
    ]
