# Generated by Django 5.2 on 2026-02-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_serviceinvoice_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinvoice',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceinvoice',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
