# Generated by Django 5.2 on 2026-02-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_serviceinvoice_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinvoice',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
