# Generated by Django 5.2 on 2026-02-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_serviceinvoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinvoice',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceinvoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI')], max_length=20, null=True),
        ),
    ]
