# Generated by Django 5.2 on 2026-03-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_serviceinvoice_upi_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinvoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('RAZORPAY', 'Razorpay')], max_length=20, null=True),
        ),
    ]
